[project]
name = "expense-tracker"
version = "1.1.1"
description = "Expense Tracker with Supabase Auth"
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.5",
    "plotly>=6.9.0",
    "streamlit>=1.61.1",
    "supabase>=2.31.0",
]

[project.optional-dependencies]
dev = ["pytest>=8.3.0"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
# Добавляем фильтр предупреждений
filterwarnings = [
    "ignore:The 'timeout' parameter is deprecated:DeprecationWarning",
    "ignore:The 'verify' parameter is deprecated:DeprecationWarning",
]

[dependency-groups]
dev = [
    "python-dotenv>=1.2.3",
]
